load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "lib",
    srcs = [
        "__init__.py",
        "lib.py",
    ],
    imports = ["."],
    visibility = ["//visibility:public"],
)
