load("//third_party:third_party.bzl", "load_third_party_libraries")

load_third_party_libraries()

load("//third_party:extra_dependencies.bzl", "load_extra_dependencies")

load_extra_dependencies()
